# Generated by Django 6.0.1 on 2026-01-23 15:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('fiscal_id', models.CharField(blank=True, max_length=50, verbose_name='Matricule fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_year_start_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, help_text="Mois où commence l'année de congés (1=Janvier)", verbose_name="Mois de début d'année de congés")),
                ('leave_year_start_day', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1, help_text="Jour où commence l'année de congés", verbose_name="Jour de début d'année de congés")),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('hr', 'Ressources Humaines'), ('employee', 'Employé'), ('manager', 'Manager'), ('raf', 'RAF (Responsable Absence Formation)')], default='employee', max_length=20, verbose_name='Rôle')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Poste')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('contract_type', models.CharField(blank=True, max_length=100, verbose_name='Type de contrat')),
                ('personal_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone personnel')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name="Contact d'urgence")),
                ('emergency_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name="Téléphone d'urgence")),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('is_approver', models.BooleanField(default=False, verbose_name='Peut valider les congés')),
                ('max_approval_level', models.PositiveIntegerField(default=1, help_text='Niveau hiérarchique maximum pour la validation (1 = N+1, 2 = N+2, etc.)', verbose_name='Niveau maximum de validation')),
                ('is_raf', models.BooleanField(default=False, verbose_name='Responsable Absence Formation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('additional_groups', models.ManyToManyField(blank=True, related_name='additional_users', to='auth.group', verbose_name='Groupes supplémentaires')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissions spécifiques à cet utilisateur.', related_name='custom_user_permissions', to='auth.permission', verbose_name='Permissions utilisateur')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.company')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du département')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.department'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la direction')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='users.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_divisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='users.division'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du workflow')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('levels', models.PositiveIntegerField(default=1, help_text="Nombre d'étapes de validation requises", verbose_name='Nombre de niveaux de validation')),
                ('level1_approver', models.CharField(choices=[('direct_manager', 'Manager direct'), ('department_manager', 'Chef de département'), ('hr', 'Ressources Humaines'), ('specific_user', 'Utilisateur spécifique')], default='direct_manager', max_length=50, verbose_name='Validateur niveau 1')),
                ('level2_approver', models.CharField(choices=[('department_manager', 'Chef de département'), ('division_manager', 'Chef de direction'), ('hr', 'Ressources Humaines'), ('specific_user', 'Utilisateur spécifique'), ('none', 'Aucun')], default='none', max_length=50, verbose_name='Validateur niveau 2')),
                ('level3_approver', models.CharField(choices=[('division_manager', 'Chef de direction'), ('hr_director', 'Directeur RH'), ('specific_user', 'Utilisateur spécifique'), ('none', 'Aucun')], default='none', max_length=50, verbose_name='Validateur niveau 3')),
                ('require_comments_on_rejection', models.BooleanField(default=True, verbose_name='Commentaires obligatoires en cas de rejet')),
                ('auto_approve_after_days', models.PositiveIntegerField(blank=True, help_text="Si vide, pas d'approbation automatique", null=True, verbose_name='Approbation automatique après X jours')),
                ('apply_to_all', models.BooleanField(default=False, verbose_name="Appliquer à toute l'entreprise")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apply_to_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs concernés')),
                ('level1_specific_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_workflows', to=settings.AUTH_USER_MODEL)),
                ('level2_specific_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2_workflows', to=settings.AUTH_USER_MODEL)),
                ('level3_specific_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level3_workflows', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='users.company')),
                ('apply_to_departments', models.ManyToManyField(blank=True, to='users.department', verbose_name='Départements concernés')),
                ('apply_to_services', models.ManyToManyField(blank=True, to='users.service', verbose_name='Services concernés')),
            ],
            options={
                'verbose_name': 'Workflow de validation',
                'verbose_name_plural': 'Workflows de validation',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.service'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=20, verbose_name='Thème')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name="Notifications dans l'application")),
                ('notify_on_approval', models.BooleanField(default=True, verbose_name="Notifier lors d'une demande à valider")),
                ('notify_on_status_change', models.BooleanField(default=True, verbose_name='Notifier lors du changement de statut')),
                ('notify_on_leave_balance', models.BooleanField(default=True, verbose_name='Notifier sur le solde de congés')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/', verbose_name='Diplôme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
    ]
