# Generated by Django 6.0.1 on 2026-01-23 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('approve', 'Approbation'), ('reject', 'Rejet'), ('view', 'Consultation'), ('export', 'Exportation'), ('import', 'Importation'), ('download', 'Téléchargement'), ('system', 'Action système'), ('other', 'Autre')], max_length=50, verbose_name="Type d'action")),
                ('module', models.CharField(choices=[('authentication', 'Authentification'), ('user_management', 'Gestion utilisateurs'), ('organization', 'Organisation'), ('leave_management', 'Gestion congés'), ('approval', 'Validation'), ('attendance', 'Présence'), ('reporting', 'Rapports'), ('profile', 'Profil'), ('settings', 'Paramètres'), ('system', 'Système')], max_length=50, verbose_name='Module')),
                ('description', models.TextField(verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('old_data', models.JSONField(blank=True, help_text='Valeurs avant la modification (format JSON)', null=True, verbose_name='Données avant modification')),
                ('new_data', models.JSONField(blank=True, help_text='Valeurs après la modification (format JSON)', null=True, verbose_name='Données après modification')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_success', models.BooleanField(default=True, verbose_name='Succès')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('duration', models.DecimalField(blank=True, decimal_places=3, help_text="Durée d'exécution de l'action", max_digits=10, null=True, verbose_name='Durée (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='users_activ_created_31380b_idx'), models.Index(fields=['user', 'created_at'], name='users_activ_user_id_f1f5e0_idx'), models.Index(fields=['action_type', 'created_at'], name='users_activ_action__aa4fd1_idx'), models.Index(fields=['module', 'created_at'], name='users_activ_module_81b171_idx')],
            },
        ),
    ]
