# Generated by Django 6.0.1 on 2026-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('workshop', 'Atelier'), ('training', 'Formation'), ('meeting', 'Réunion'), ('other', 'Autre')], default='workshop', max_length=50, verbose_name='Type de présence')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_datetime', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_datetime', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='attendance_certificates/', verbose_name='Certificat/Attestation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Récurrent chaque année')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.PositiveIntegerField(verbose_name='Niveau de validation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('is_delegated', models.BooleanField(default=False, verbose_name='Délégation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
            ],
            options={
                'verbose_name': 'Validation de congé',
                'verbose_name_plural': 'Validations de congé',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Jours acquis')),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Jours utilisés')),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Jours en attente')),
                ('carried_over_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Jours reportés')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Dernier calcul')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congé',
            },
        ),
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Jour ouvrable')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Jour férié')),
                ('day_type', models.CharField(choices=[('full_day', 'Journée complète'), ('morning', 'Matin'), ('afternoon', 'Après-midi'), ('specific_hours', 'Heures spécifiques')], default='full_day', max_length=20, verbose_name='Type de jour')),
                ('duration', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Durée en jours')),
            ],
            options={
                'verbose_name': 'Jour de congé',
                'verbose_name_plural': 'Jours de congé',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('start_day_type', models.CharField(choices=[('full_day', 'Journée complète'), ('morning', 'Matin'), ('afternoon', 'Après-midi'), ('specific_hours', 'Heures spécifiques')], default='full_day', max_length=20, verbose_name='Type de jour début')),
                ('end_day_type', models.CharField(choices=[('full_day', 'Journée complète'), ('morning', 'Matin'), ('afternoon', 'Après-midi'), ('specific_hours', 'Heures spécifiques')], default='full_day', max_length=20, verbose_name='Type de jour fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nombre total de jours')),
                ('working_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nombre de jours ouvrables')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('contact_during_leave', models.CharField(blank=True, max_length=255, verbose_name='Contact pendant le congé')),
                ('phone_during_leave', models.CharField(blank=True, max_length=20, verbose_name='Téléphone pendant le congé')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='Justificatif')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='draft', max_length=20, verbose_name='Statut')),
                ('current_approval_level', models.PositiveIntegerField(default=1, verbose_name='Niveau de validation actuel')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de rejet')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du type')),
                ('category', models.CharField(choices=[('paid', 'Congés payés'), ('unpaid', 'Congés sans solde'), ('sick', 'Congés maladie'), ('maternity', 'Congé maternité'), ('paternity', 'Congé paternité'), ('training', 'Formation/Atelier'), ('special', 'Congé exceptionnel'), ('other', 'Autre')], default='paid', max_length=50, verbose_name='Catégorie')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Nécessite une validation')),
                ('requires_document', models.BooleanField(default=False, verbose_name='Nécessite un justificatif')),
                ('deduct_from_balance', models.BooleanField(default=True, verbose_name='Déduit du solde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour illimité', null=True, verbose_name='Nombre maximum de jours par an')),
                ('max_consecutive_days', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour illimité', null=True, verbose_name='Nombre maximum de jours consécutifs')),
                ('min_notice_days', models.PositiveIntegerField(default=0, verbose_name='Délai de préavis minimum (jours)')),
                ('color', models.CharField(default='#007bff', help_text="Couleur HEX pour l'affichage", max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS pour l'icône", max_length=50, verbose_name='Icône')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('leave_request', 'Nouvelle demande de congé'), ('leave_approved', 'Congé approuvé'), ('leave_rejected', 'Congé rejeté'), ('leave_cancelled', 'Congé annulé'), ('approval_required', 'Validation requise'), ('reminder', 'Rappel'), ('balance_low', 'Solde faible'), ('system', 'Message système')], max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Normal'), (2, 'Important'), (3, 'Urgent')], default=1, verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('leave_summary', 'Résumé des congés'), ('attendance', 'Présence'), ('balance', 'Soldes'), ('custom', 'Personnalisé')], max_length=50, verbose_name='Type de rapport')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Format de sortie')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Planifié')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], max_length=20, verbose_name='Fréquence de planification')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
